import '../styles/globals.css'
import type { AppProps } from 'next/app'
import  Head  from 'next/head'
// import Image from "next/head"
import Link from 'next/link'

import styles from "../styles/App.module.css"

import { Box, Heading, Text, ThemeProvider, theme } from '@chakra-ui/react'
import { Image } from '@chakra-ui/react'

export default function App({ Component, pageProps }: AppProps) {
  const I1 = "https://gallery-cdn.breezy.hr/87ea76b4-b258-455d-824f-9dd0a6955fb3/FB-Atardecer 1.jpg"
  
  return(
    <>
      <ThemeProvider theme={theme}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
          <Box>
              <Link href={`/`}>
              <Heading
                textAlign={"center"}
                fontWeight={600}
                fontSize={{ base: '3xl', sm: '4xl', md: '6xl' }}
                lineHeight={'110%'}>
                Fly
                <Text as={'span'} color={'orange.400'}>
                  Tincho
                </Text>
              </Heading>
              </Link>
          
            <Component {...pageProps} />
        </Box>
      </ThemeProvider>
    </>
    
  )
}
