import '../styles/globals.css'
import type { AppProps } from 'next/app'
import  Head  from 'next/head'
import Image from "next/head"
import Link from 'next/link'

import styles from "../styles/App.module.css"

export default function App({ Component, pageProps }: AppProps) {
  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
       
        <div className={styles.center}>
            <Link href={`/`}><h1>FlyBondew (home)</h1></Link>
        </div>

        <Component {...pageProps} />

      </main>
    </>
  )
}
